// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix']
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    DataChart: typeof import('./src/views/dashboard/data-explorer/components/data-view/components/data-chart.vue')['default']
    DataExplorer: typeof import('./src/views/dashboard/data-explorer/index.vue')['default']
    DataGrid: typeof import('./src/views/dashboard/data-explorer/components/data-view/components/data-grid.vue')['default']
    DataView: typeof import('./src/views/dashboard/data-explorer/components/data-view/index.vue')['default']
    Editor: typeof import('./src/views/dashboard/data-explorer/components/editor.vue')['default']
    Favorite: typeof import('./src/views/dashboard/data-explorer/components/favorite.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    Log: typeof import('./src/views/dashboard/data-explorer/components/log.vue')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    NotFound: typeof import('./src/views/not-found/index.vue')['default']
    Redirect: typeof import('./src/views/redirect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/tab-bar/index.vue')['default']
    TabItem: typeof import('./src/components/tab-bar/tab-item.vue')['default']
    TableList: typeof import('./src/views/dashboard/data-explorer/components/table-list.vue')['default']
  }
}
