version: "3.8"

services:
  greptimedb:
    image: greptime/greptimedb:latest
    command: "standalone start --http-addr=0.0.0.0:4000"
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - e2e-net

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.e2e
    environment:
      VITE_API_BASE: "http://greptimedb:4000"
    depends_on:
      greptimedb:
        condition: service_healthy
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/dashboard/query"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - e2e-net

networks:
  e2e-net:
    driver: bridge